Import libraries that may be necessary

In [16]:
#important 
import numpy as np
import random

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
from sklearn.preprocessing import LabelEncoder
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_val_score


from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score

# for visualisation
import matplotlib.pyplot as plt
from sklearn.tree import export_graphviz
from IPython.display import Image  
from subprocess import call

import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits = load_digits() #load data for your notebook
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

Determine which columns will be used as your X and Y variables that are dependent on one another

In [17]:
X = digits['target_names']
y = digits['images'] 

In [18]:
img_index =25
plt.show()
print(y[img_index])

[[ 0.  0. 12.  8.  8.  7.  0.  0.]
 [ 0.  3. 16. 16. 11.  7.  0.  0.]
 [ 0.  2. 14.  1.  0.  0.  0.  0.]
 [ 0.  5. 14.  5.  0.  0.  0.  0.]
 [ 0.  2. 15. 16.  9.  0.  0.  0.]
 [ 0.  0.  0.  2. 16.  2.  0.  0.]
 [ 0.  0.  4.  8. 16.  4.  0.  0.]
 [ 0.  0. 11. 14.  9.  0.  0.  0.]]


RandomForestClassifier for classifcation and regression to make your model more smooth

In [19]:
clf = RandomForestClassifier()

In [20]:
RandomForestClassifier(bootstrap=True,class_weight=None,criterion='gini',max_depth=None,max_features='auto',max_leaf_nodes=None,min_impurity_split=1e-07, min_samples_leaf=1,min_samples_split=2,min_weight_fraction_leaf=0.0,n_estimators=10,
n_jobs=1,oob_score=False,random_state=None,verbose=0,warm_start=False)

RandomForestClassifier(min_impurity_split=1e-07, n_estimators=10, n_jobs=1)

In [21]:
#split data into training, development and test set.
X_train, X_dev, y_train, y_dev = train_test_split(
    digits.data, digits.target, test_size = 0.25, random_state = 0)
X_train, X_test, y_train, y_test = train_test_split(
    digits.data, digits.target, test_size = 0.25, random_state = 0)

Decision trees perform classification without needing too much computation. I chose logistic regression to find the relationship between a dependent variable and either one independent variable or multiple independent variables

I set max_iter to 10000 because it will help with errors because the dataset is quite big

In [22]:
# for decision tree
splitter1='random'
# for Logistic Regression
max_iter1=10000 

In [23]:
# Print confusion matrices for your two competitor models’ predictions on the
# test set.

# create  first model
logr = LogisticRegression(max_iter=max_iter1)
# fit the model
logr.fit(X_train, y_train)

#make prediction
predictions1 = logr.predict(X_test)

#calculate confusion matrix
cm = confusion_matrix(y_test, predictions1)
print(cm)

[[37  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  2  1]
 [ 0  0 41  3  0  0  0  0  0  0]
 [ 0  0  0 44  0  0  0  0  1  0]
 [ 0  0  0  0 37  0  0  1  0  0]
 [ 0  0  0  0  0 46  0  0  0  2]
 [ 0  1  0  0  0  0 51  0  0  0]
 [ 0  0  0  1  1  0  0 46  0  0]
 [ 0  3  1  0  0  0  1  0 43  0]
 [ 0  0  0  0  0  1  0  0  2 44]]


In [24]:
# create second model
dt = DecisionTreeClassifier(splitter=splitter1)
# fit the model
dt.fit(X_train, y_train)

#make prediction
predictions2 = dt.predict(X_test)

#calculate confusion matrix
cm = confusion_matrix(y_test, predictions2)
print(cm)

[[37  0  0  0  0  0  0  0  0  0]
 [ 0 36  2  0  1  0  0  1  2  1]
 [ 1  4 35  1  0  0  0  2  1  0]
 [ 0  0  1 38  0  0  1  1  0  4]
 [ 0  1  0  0 34  0  1  1  0  1]
 [ 1  1  0  2  3 37  1  0  2  1]
 [ 0  1  0  0  1  0 50  0  0  0]
 [ 0  1  2  0  1  1  0 41  2  0]
 [ 0  3  4  1  2  0  1  1 35  1]
 [ 0  1  2  0  0  4  0  0  0 40]]


Both of the models struggled with the 5th class and had the lowest numbers. The Decision tree model the 2nd class struggled with the 4th class. The second class Logistic Regression struggled with the first class.

In [25]:
# accuracy score for model 1 and 2
a1 = accuracy_score(y_test, predictions1)
print("Logistic Regression accuracy score ", a1)
a2 = accuracy_score(y_test, predictions2)
print("Decision Tree accuracy score:", a2)

print("\n")

# precision score for model 1 and 2
p1 = precision_score(y_test, predictions1, average='micro')
print("Logistic Regression precision score ", p1)
p2 = precision_score(y_test, predictions2, average='micro')
print("Decision Tree precision score:", p2)

print("\n")

# recall score for model 1 and 2
r1 = recall_score(y_test, predictions1, average='micro')
print("Logistic Regression recall score ", r1)
r2 = recall_score(y_test, predictions2, average='micro')
print("Decision Tree recall score:", r2)

print("\n")

# f1 score for model 1 and 2
f1 = f1_score(y_test, predictions1, average='micro')
print("Logistic Regression f1 score ", f1)
f2 = f1_score(y_test, predictions2, average='micro')
print("Decision Tree f1 score:", f2)

Logistic Regression accuracy score  0.9533333333333334
Decision Tree accuracy score: 0.8511111111111112


Logistic Regression precision score  0.9533333333333334
Decision Tree precision score: 0.8511111111111112


Logistic Regression recall score  0.9533333333333334
Decision Tree recall score: 0.8511111111111112


Logistic Regression f1 score  0.9533333333333334
Decision Tree f1 score: 0.8511111111111112


The Logistic Regression model has the highest score and had a better performance overall and did the best job. 